cart = ["apple", "banana", "milk", "bread", "apple", "eggs"]
apple_count = cart.count("apple")
print(f"Number of apples: {apple_count}")

milk_position = cart.index("milk")
print("========================")
print('Using varible milk_position = cart.index("milk")')
print(f"Position of Milk: {milk_position}")
print("========================")
print('Usnig {cart.index("milk")}')
print(f"Positon of Milk: {cart.index("milk")}")
print(f"Positon of Apple: {cart.index("apple")}")
print("========================")
cart.remove("apple")
print(cart)
print("========================")
print(f"Positon of Apple: {cart.index("apple")}")
print(f"Remove item using pop: {cart.pop()}")
print("Is banana in the cart?", "banana" in cart)
print(f"Final cart {cart}")